export const ContentActionTypes = {
  FETCH_CONTENT_REQUEST: 'FETCH_CONTENT_REQUEST',
  FETCH_CONTENT_SUCCESS: 'FETCH_CONTENT_SUCCESS',
  FETCH_CONTENT_FAILURE: 'FETCH_CONTENT_FAILURE',
  POST_CONTENT_REQUEST: 'POST_CONTENT_REQUEST',
  POST_CONTENT_SUCCESS: 'POST_CONTENT_SUCCESS',
  POST_CONTENT_FAILURE: 'POST_CONTENT_FAILURE',
  CLEAR_CONTENT: 'CLEAR_CONTENT',
  REFRESH_CONTENT_SUCCESS: 'REFRESH_CONTENT_SUCCESS',
  REFRESH_CONTENT_REQUEST: 'REQUEST_CONTENT_REQUEST',
  REFRESH_CONTENT_FAILURE: 'REQUEST_CONTENT_FAILURE'
};
